# Copyright © 2026 Brent Tunnicliff <brent@tunnicliff.dev>

name: Pipeline

on:
  push:
  workflow_dispatch:

env:
  DEMO_PROJECT: "Demo.xcodeproj"
  DEMO_SCHEME: "Demo"
  DEMO_WATCH_SCHEME: "Demo Watch App"
  PACKAGE_SCHEME: "REPLACE_ME-Package"
  RUNS_ON: "macOS"
  SIMULATOR_VERSION: "26.2"
  XCODE_PATH: "/Applications/Xcode_26.3.app"

jobs:
  package:
    strategy:
      # Don't cancel the other matrix values if one fails.
      fail-fast: false
      matrix:
        target: [
          { platform: "iOS", simulator_version: "${{ env.SIMULATOR_VERSION }}" },
          { platform: "tvOS", simulator_version: "${{ env.SIMULATOR_VERSION }}" },
          { platform: "watchOS", simulator_version: "${{ env.SIMULATOR_VERSION }}" },
          { platform: "visionOS", simulator_version: "${{ env.SIMULATOR_VERSION }}" },

          # macOS runs on the host and doesn't need a simulator.
          { platform: "macOS", simulator_version: "" }
        ]
    uses: Brent-Tunnicliff/workflow-common-apple/.github/workflows/xcodebuild.yml@v2
    with:
      platform: "${{ matrix.target.platform }}"
      runs_on: "${{ env.RUNS_ON }}"
      scheme: "${{ env.PACKAGE_SCHEME }}"
      simulator_version: "${{ matrix.target.simulator_version }}"
      xcode_path: "${{ env.XCODE_PATH }}"

  demo:
    strategy:
      # Don't cancel the other matrix values if one fails.
      fail-fast: false
      matrix:
        target: [
          { platform: "iOS", simulator_version: "${{ env.SIMULATOR_VERSION }}" },
          { platform: "tvOS", simulator_version: "${{ env.SIMULATOR_VERSION }}" },
          { platform: "watchOS", simulator_version: "${{ env.SIMULATOR_VERSION }}" },
          { platform: "visionOS", simulator_version: "${{ env.SIMULATOR_VERSION }}" },

          # macOS runs on the host and doesn't need a simulator.
          { platform: "macOS", simulator_version: "" }
        ]
    uses: Brent-Tunnicliff/workflow-common-apple/.github/workflows/xcodebuild.yml@v2
    with:
      platform: "${{ matrix.target.platform }}"
      runs_on: "${{ env.RUNS_ON }}"
      # watch has its own scheme and target.
      scheme: "${{ case(
        matrix.target.platform == 'watchOS', $DEMO_WATCH_SCHEME,
        $DEMO_SCHEME
      }}"
      simulator_version: "${{ matrix.target.simulator_version }}"
      # No tests configured for demo app.
      skip_tests: true
      xcode_path: "${{ env.XCODE_PATH }}"
    working-directory: ./Demo

  lint:
    uses: Brent-Tunnicliff/workflow-common-apple/.github/workflows/lint.yml@v2
    with:
      runs_on: "macos-26"

